---
title: "General B-Cell Repertoire Analysis Based on Merged Replicates"
output:
  html_document:
    df_print: paged
---

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
source("Main.R")
library(Peptides)
library(gtools)

knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
```


```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}

plotConstantRegion <- function(contigs, intRan=100){
  
   df <- as.data.frame(table(contigs[,c("C_CALL")]))
   df$genIgType <- sapply(df$Var1, function(x){substr(x,1,4)})
   
   dT <- as.data.table(df)[,sum(Freq),by=genIgType]
   df <- merge(df, dT, by="genIgType")
   df$genIgType <- paste0(df$genIgType, ", ", df$V1)
    
   
   df$Freq <- df$Freq / sum(df$Freq)
   df$Var1 <- sapply(df$Var1, function(x){substr(x,4,5)})
   df$Freq <- 100*df$Freq
   p <- ggplot(df, aes(x=Var1, y=Freq)) +
         geom_bar(stat="identity", color="black", fill="lightblue", position = position_dodge())+
         facet_wrap(~genIgType, scales = "free_x")+
         ylab("Percent of cells (%)")+
         xlab("")+
         scale_y_continuous(breaks = seq(0,100,10), labels=seq(0,100,10))
   return(p)
}
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=15, fig.height=5}
plotSomaticMutationBars <- function(contigs, heavyOrLight="heavy"){
    
    if(heavyOrLight == "heavy"){
      db_obs <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT",
                                germlineColumn="GERMLINE_IMGT",
                                regionDefinition=IMGT_V_BY_REGIONS,
                                frequency=TRUE, 
                                nproc=1)
      db_obs <- db_obs[db_obs$C_CALL_General %in% c("IGHA","IGHG","IGHM"),]
        
      muCols <- grep("CELL|MU_FREQ|C_CALL_General", colnames(db_obs))
      tt <-  db_obs[,muCols]
      
      dft <- as.data.table(db_obs)[,.(.N),by=C_CALL_General]
      colnames(dft) <- c("C_CALL_General", "cellCount")
      
    }else if(heavyOrLight == "light"){
      db_obs <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT_LIGHT",
                                germlineColumn="GERMLINE_IMGT_LIGHT",
                                regionDefinition=IMGT_V_BY_REGIONS,
                                frequency=TRUE, 
                                nproc=1)
      
      db_obs <- db_obs[db_obs$C_CALL_LIGHT_General %in% c("IGK","IGL"),]
        
      muCols <- grep("CELL|MU_FREQ|C_CALL_LIGHT_General", colnames(db_obs))
      tt <- db_obs[,muCols]
      tt$C_CALL_General <- tt$C_CALL_LIGHT_General
      tt$C_CALL_LIGHT_General <- NULL
      
      dft <- as.data.table(db_obs)[,.(.N),by=C_CALL_LIGHT_General]
      colnames(dft) <- c("C_CALL_General", "cellCount")
    }
  
      db_obsPlot <- melt(tt, id.vars = c("CELL","C_CALL_General"))
      db_obsPlot$variable <- sapply(db_obsPlot$variable, function(x){strsplit(as.character(x),"MU_FREQ_")[[1]][2]})
      db_obsPlot$region <- sapply(db_obsPlot$variable, function(x){strsplit(x,"_")[[1]][1]})
      db_obsPlot$mutationType <- sapply(db_obsPlot$variable, function(x){strsplit(x,"_")[[1]][2]})
      db_obsPlot$cellRegion <- paste0(db_obsPlot$CELL,"_",db_obsPlot$region,"_",db_obsPlot$C_CALL_General)
      db_obsPlot <- merge(db_obsPlot, dft, by="C_CALL_General")
      db_obsPlot$C_CALL_General <- paste0(db_obsPlot$C_CALL_General, ", ",db_obsPlot$cellCount )
      db_obsPlot$variable <- factor(db_obsPlot$variable, levels=c("CDR1_S", "CDR1_R","CDR2_S", "CDR2_R","FWR1_S", "FWR1_R","FWR2_S", "FWR2_R","FWR3_S", "FWR3_R"))
     
      cList = list(c("CDR1_S", "CDR1_R"),
                   c("CDR2_S", "CDR2_R"),
                   c("FWR1_S", "FWR1_R"),
                   c("FWR2_S", "FWR2_R"), 
                   c("FWR3_S", "FWR3_R"))
      p2 <- ggpaired(db_obsPlot, x="variable", y="value", fill="mutationType", id="cellRegion", line.size = 0.02,
                     point.size = 0.1,
                     facet.by = "C_CALL_General") +
                     stat_compare_means(method="wilcox.test",paired = TRUE,
                                comparisons = cList,
                                color="red",
                                label.y= 0.55, aes(label = ..p.signif..))+
              ggtitle(paste0(sampleName, " ", heavyOrLight, " chain mutations")) +
              xlab("") +
              ylab("Mutation frequency") +
              theme_bw()+theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "top")
    
    
    
      return(p2)
}
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
plotSomaticMutationNumbers <- function(contigs){
  
   db_obsHeavy <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT",
                                germlineColumn="GERMLINE_IMGT",
                                regionDefinition=IMGT_V_BY_SEGMENTS,
                                frequency=FALSE, 
                                nproc=1)
   db_obsLight <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT_LIGHT",
                                germlineColumn="GERMLINE_IMGT_LIGHT",
                                regionDefinition=IMGT_V_BY_SEGMENTS,
                                frequency=FALSE, 
                                nproc=1)
   
        
   db_obsHeavy <- db_obsHeavy[,c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "MU_COUNT_V_R", "MU_COUNT_V_S")]
   db_obsLight <- db_obsLight[,c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "MU_COUNT_V_R", "MU_COUNT_V_S")]
   
   colnames(db_obsHeavy) <- c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "VH_R", "VH_S")
   colnames(db_obsLight) <- c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "VL_R", "VL_S")

   db_obs_all <- merge(db_obsHeavy, db_obsLight, by=c("CELL", "C_CALL_General", "C_CALL_LIGHT_General"))
   dft <- as.data.table(db_obs_all)[,.(.N),by=C_CALL_General]
   colnames(dft) <- c("C_CALL_General", "cellCount")
   
   
   db_obs_all$V_heavy <- db_obs_all$VH_R + db_obs_all$VH_S
   db_obs_all$V_light <- db_obs_all$VL_R + db_obs_all$VL_S
   
   db_obs_melted <- melt(db_obs_all[,c("C_CALL_General", "C_CALL_LIGHT_General", "V_heavy", "V_light")], 
                         id.vars = c( "C_CALL_General", "C_CALL_LIGHT_General"))
   db_obs_melted$variable <- as.character(db_obs_melted$variable)
   db_obs_melted[db_obs_melted$variable=="V_heavy", "variable"] <- "VH"
   db_obs_melted[db_obs_melted$variable=="V_light" & db_obs_melted$C_CALL_LIGHT_General == "IGL" , "variable"] <- "VL"
   db_obs_melted[db_obs_melted$variable=="V_light" & db_obs_melted$C_CALL_LIGHT_General == "IGK" , "variable"] <- "VK"

   db_obs_melted <- merge(db_obs_melted, dft, by= "C_CALL_General")
   numberOfUniqueH <- length(unique(db_obs_melted$C_CALL_General))
   db_obs_melted$C_CALL_General <- as.character(db_obs_melted$C_CALL_General)
   k <- as.data.frame(combinations(numberOfUniqueH,2, unique(db_obs_melted$C_CALL_General)))
   k <- data.frame(apply(k,1,function(x){return(c(as.character(x[[1]]), as.character(x[[2]])))}), stringsAsFactors = F)

   p3 <- ggplot(db_obs_melted, aes(x=C_CALL_General, y=value)) + 
     facet_wrap(~variable, scales = "free_x")+
     geom_violin(trim=FALSE)+
     stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")+
     stat_summary(fun.data = n_fun, geom = "text", size=3)+
     stat_compare_means(method="wilcox.test",paired = FALSE,
                                comparisons = k,
                                color="red",
                                label.y.npc = c(80,80,90), aes(label = ..p.signif..))+
     xlab("")+
     ylab("Number of mutations")
   
   return(p3)
}
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
plotCellCountDistribution <- function(contigs){
  contigs <- as.data.table(contigs)
  contigs <- contigs[order(C_CALL_General,C_CALL_LIGHT_General),]
  contigs$C_CALL_ALL <- paste0(contigs$C_CALL_General,"_",contigs$C_CALL_LIGHT_General)
  contigs[,NumberOfIgTypeCells := length(unique(CELL)),by=C_CALL_ALL]
  datT <- unique(contigs[,c("C_CALL_ALL", "NumberOfIgTypeCells")])
  datT$fraction = as.numeric(format(round(datT$NumberOfIgTypeCells / sum(datT$NumberOfIgTypeCells), 2), nsmall = 2))
  datT = datT[order(datT$NumberOfIgTypeCells), ]
  datT$ymax = cumsum(datT$fraction)
  datT$ymin = c(0, head(datT$ymax, n=-1))
  datT <- datT[datT$fraction > 0.001,]
  datT$C_CALL_ALL <- factor(datT$C_CALL_ALL , levels = rev(as.character(datT$C_CALL_ALL) ))
   
  # Make the plot
  p = ggplot(datT, aes(fill=C_CALL_ALL, ymax=ymax, ymin=ymin, xmax=4, xmin=3)) +
     geom_rect() +
     coord_polar(theta="y") +
     xlim(c(0, 4)) +
     theme(panel.grid=element_blank()) +
     theme(axis.text=element_blank()) + theme_void()+
     theme(axis.ticks=element_blank(), legend.title = element_blank()) +
     annotate("text", x = 0, y = 0, label = paste0(sum(datT$NumberOfIgTypeCells)), size=8) +
     scale_fill_manual(values = colorRampPalette(brewer.pal(200, "Paired"))(nrow(datT)))+
     labs(title="")+geom_text(aes(label=NumberOfIgTypeCells,x=4,y=(ymin+ymax)/2),inherit.aes = TRUE, show.legend = FALSE)
  return(p)
}
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
plotClonalDistribution <- function(inClones, titleStr){
  inClones <- as.data.table(inClones)
  inClones[,NumberOfClonalCells := length(unique(CELL)),by=CLONE]
  inClones <- inClones[order(-NumberOfClonalCells),]
  datT <- unique(inClones[,c("CLONE","NumberOfClonalCells")])

  for(j in 1:max(datT$NumberOfClonalCells)){
    if(j==1){
      datT[datT$NumberOfClonalCells==j,"raw_clonotype_id"] <- paste0(j, " cell")
    }else{
      datT[datT$NumberOfClonalCells==j,"raw_clonotype_id"] <- paste0(j, " cells")
    }
  }   
  datT[,numberOfClones := .(.N),by=.(raw_clonotype_id)]
  datT[,totalNumberOfCells := sum(NumberOfClonalCells),by=.(raw_clonotype_id)]
  datT$NumberOfClonalCells <- NULL
  datT$CLONE <- NULL
  
  datT <- unique(datT)
  
  datT$fraction = as.numeric(format(round(datT$totalNumberOfCells / sum(datT$totalNumberOfCells), 2), nsmall = 2))
  datT = datT[order(datT$totalNumberOfCells), ]
  datT$ymax = cumsum(datT$fraction)
  datT$ymin = c(0, head(datT$ymax, n=-1))
  datT <- datT[datT$fraction > 0.001,]
  datT$raw_clonotype_id <- factor(datT$raw_clonotype_id , levels = rev(as.character(datT$raw_clonotype_id) ))
   # Make the plot
  p = ggplot(datT, aes(fill=raw_clonotype_id, ymax=ymax, ymin=ymin, xmax=4, xmin=3)) +
     geom_rect() +
     coord_polar(theta="y") +
     xlim(c(0, 4)) +
     theme(panel.grid=element_blank()) +
     theme(axis.text=element_blank()) + theme_void()+
     theme(axis.ticks=element_blank(), legend.title = element_blank()) +
     annotate("text", x = 0, y = 0, label = paste0(sum(datT$totalNumberOfCells)), size=8) +
     scale_fill_manual(values = colorRampPalette(brewer.pal(200, "Dark2"))(nrow(datT)))+
     labs(title="")+geom_text(aes(label=numberOfClones,x=4,y=(ymin+ymax)/2),inherit.aes = TRUE, show.legend = FALSE)+ggtitle(titleStr)
  return(p)
  
}
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
plotIgRepertoire <- function(contigs, heavyOrLight="heavy", lambdaOrKappa="NULL"){
  
  if(heavyOrLight == "heavy"){
    tp <- contigs[,c("V_CALL", "J_CALL", "C_CALL_General","CLONE")]
    labelV <- "VH"
    labelJ <- "JH"
  }else if(heavyOrLight == "light"){
    tp <- contigs[,c("V_CALL_LIGHT", "J_CALL_LIGHT", "C_CALL_General","C_CALL_LIGHT_General","CLONE")]
   
    if(lambdaOrKappa == "lambda"){
      tp <- tp[tp$C_CALL_LIGHT_General=="IGL",]
      labelV <- "VL"
      labelJ <- "JL"
    }else if(lambdaOrKappa == "kappa"){
      tp <- tp[tp$C_CALL_LIGHT_General=="IGK",]
      labelV <- "VK"
      labelJ <- "JK"
    }
    tp$C_CALL_LIGHT_General <- NULL
    colnames(tp) <- c("V_CALL", "J_CALL", "C_CALL_General","CLONE")
  }
  
    tpSplit <- split(tp, f = tp$CLONE)
    tpSplit <- lapply(tpSplit, function(x){return(x[1,])})
    tpSplit <- do.call(rbind, tpSplit)
  
    tpSplit$V_CALL <- sapply(tpSplit$V_CALL, function(x){substr(x,4,5)})
    tpSplit$J_CALL <- sapply(tpSplit$J_CALL, function(x){substr(x,4,5)})
    
    vDF <- data.frame(table(tpSplit[,c("V_CALL","C_CALL_General")]))
    jDF <- data.frame(table(tpSplit[,c("J_CALL","C_CALL_General")]))
    
    vT <- as.data.table(vDF)[,sum(Freq),by=C_CALL_General]
    vDF <- merge(vDF, vT, by="C_CALL_General")
    vDF$C_CALL_General <- paste0(vDF$C_CALL_General, ", ", vDF$V1)
    
    jT <- as.data.table(jDF)[,sum(Freq),by=C_CALL_General]
    jDF <- merge(jDF, jT, by="C_CALL_General")
    jDF$C_CALL_General <- paste0(jDF$C_CALL_General, ", ", jDF$V1)
    
    vDF$Freq <- (vDF$Freq / sum(vDF$Freq))*100
    pV <-ggplot(vDF, aes(x=V_CALL, y=Freq, fill=V_CALL)) +
         geom_bar(stat="identity", color="black")+
         ylab(paste0(labelV," (%)"))+
         xlab("")+
         facet_wrap(~C_CALL_General, nrow = 1)+ theme_bw()+
         scale_fill_brewer(palette = "Dark2")+theme(legend.position = "none")
    
    jDF$Freq <- (jDF$Freq / sum(jDF$Freq))*100
    pJ <-ggplot(jDF, aes(x=J_CALL, y=Freq, fill=J_CALL)) +
         geom_bar(stat="identity", color="black")+
         ylab(paste0(labelJ, " (%)"))+
         xlab("")+
         facet_wrap(~C_CALL_General, nrow = 1)+ theme_bw()+
         scale_fill_brewer(palette = "Dark2")+theme(legend.position = "none")
    
    return(list(pV=pV, pJ=pJ))
}

```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
plotAAChemicalBoxplot <- function(contigs, xA, yA, YLStr, lYH){
   cList = list(c("IGHG", "IGHA"), c("IGHA", "IGHM"), c("IGHG", "IGHM"))
   p <- ggboxplot(contigs, x = xA, y = yA,
          fill = "C_CALL_General",remove = "point",
          size = 0.1, bxp.errorbar = T)+
    stat_compare_means(method="wilcox.test",
                                comparisons = cList,
                                color="red",
                                label.y= lYH, aes(label = ..p.signif..))+
    xlab("")+ylab(YLStr)+
     scale_fill_brewer(palette = "Dark2")+
     theme(legend.position = "None")+
     stat_summary(fun.data = n_fun, geom = "text", size=5)
   
   return(p)
}

plotCDR3_properties <- function(contigs){
  
  contigs <- aminoAcidProperties(contigs, seq="JUNCTION", nt=TRUE, trim=TRUE, label="CDR3")
  contigs$JUNCTION_aa <-  sapply(contigs$JUNCTION,
                                 function(x){paste(translate( s2c(x)), collapse = "")})
  

  contigs$CDR3_posChargeNo <- sapply(contigs$JUNCTION, function(x){ 
    k <- translate(s2c(x))
    return(length(which(charge(k[2:(length(k)-1)] ) > 0)) )
    } )
  
  
  
  p1 <- plotAAChemicalBoxplot(contigs,
                        xA="C_CALL_General",
                        yA="CDR3_AA_LENGTH",
                        YLStr="CDR3 AA Length",
                        lYH=c(30,35,40))
  
  p2 <- plotAAChemicalBoxplot(contigs,
                        xA="C_CALL_General",
                        yA="CDR3_AA_CHARGE",
                        YLStr="CDR3 AA Charge",
                        lYH=c(5,8,10))
   
  p3 <- plotAAChemicalBoxplot(contigs,
                        xA="C_CALL_General",
                        yA="CDR3_AA_GRAVY",
                        YLStr="CDR3 AA Hydrophobicity",
                        lYH=c(4,5,6))
  
  p4 <- plotAAChemicalBoxplot(contigs,
                        xA="C_CALL_General",
                        yA="CDR3_AA_BASIC",
                        YLStr="CDR3 Basic Residues",
                        lYH=c(0.4,0.5,0.6)) 
  
  p5 <- plotAAChemicalBoxplot(contigs,
                        xA="C_CALL_General",
                        yA="CDR3_AA_POLARITY",
                        YLStr="CDR3 Polarity",
                        lYH=c(10,12,14)) 
  
   p6 <- plotAAChemicalBoxplot(contigs,
                        xA="C_CALL_General",
                        yA="CDR3_AA_ACIDIC",
                        YLStr="CDR3 Acidic Residues",
                        lYH=c(0.7,0.8,0.9)) 
   
   return(list(p1=p1, p2=p2, p3=p3, p4=p4, p5=p5, p6=p6))
}
```


```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}

plotRepertoireAnalysis <- function(sampleName){
    allContigs <- read.table(paste0(dataDir,"/MergedVDJReplicates/",sampleName,"/filtered_single_light_heavy_paired_clone-pass.tab"),
                             sep="\t", header=TRUE, stringsAsFactors = F)
    allContigs <- allContigs[allContigs$C_CALL != "",]
    allContigs$C_CALL_General <- sapply(allContigs$C_CALL, function(x){substr(x,1,4)})
    allContigs$C_CALL_LIGHT_General <- sapply(allContigs$C_CALL_LIGHT, function(x){substr(x,1,3)})
    allContigs <- allContigs[allContigs$C_CALL_LIGHT_General %in% c("IGL", "IGK"),]
    
    pA <- plotConstantRegion(allContigs)
    pB1 <- plotSomaticMutationBars(contigs=allContigs, heavyOrLight="heavy")
    pB2 <- plotSomaticMutationBars(contigs=allContigs, heavyOrLight="light")
    pC <- plotSomaticMutationNumbers(contigs=allContigs)
    
    pD0 <- plotCellCountDistribution(allContigs)
    pD1 <- plotClonalDistribution(inClones=allContigs[allContigs$C_CALL_General=="IGHG",],
                                  titleStr=paste0(sampleName, " IgG Cells"))
    pD2 <- plotClonalDistribution(inClones=allContigs[allContigs$C_CALL_General=="IGHA",],
                                  titleStr=paste0(sampleName, " IgA Cells"))
    pD3 <- plotClonalDistribution(inClones=allContigs[allContigs$C_CALL_General=="IGHM",],
                                  titleStr=paste0(sampleName, " IgM Cells"))

    PE<- plotIgRepertoire(allContigs, heavyOrLight="heavy")
    pE1 <- PE$pV
    pE2 <- PE$pJ
    PE2 <- plotCDR3_properties(allContigs)
    pE3 <- PE2$p1
    pE4 <- PE2$p2
    pE5 <- PE2$p3
    pE6 <- PE2$p4
    pE7 <- PE2$p5
    pE8 <- PE2$p6
    
    PF<- plotIgRepertoire(contigs = allContigs, heavyOrLight="light", lambdaOrKappa="kappa")
    pF1 <- PF$pV
    pF2 <- PF$pJ
    PF2<- plotIgRepertoire(allContigs, heavyOrLight="light", lambdaOrKappa="lambda")
    pF3 <- PF2$pV
    pF4 <- PF2$pJ
    
    print(plot_grid(plotlist = list(pA, pC, pB1, pB2),
              nrow = 2, rel_heights = c(2,3)))
    
    print(plot_grid(plotlist = list(pD0, pD1, pD2, pD3),
              nrow = 1))
    
    print(plot_grid(plotlist = list(pE3, pE4, pE5, pE6, pE7, pE8),
              nrow = 2))
    
     print(plot_grid(plotlist = list(pE1, pE2, pF1, pF2, pF3, pF4),
              nrow = 3))
    
}

```


```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=15, fig.height=10}
samples$DonorID=factor(samples$DonorID, levels = c("UC3","UC10","UC15","UC16","UC17","UC18","UC20","UC4","UC9","UC14","UC19","Healthy1","Healthy2","Healthy3","Healthy4"))

samples <- samples[order(samples$DonorID),]

for(sampleName in unique(samples$CanonicalSampleName)){
  print(paste0("#################" ,sampleName , "######################"))
  plotRepertoireAnalysis(sampleName)
  
}
```

