---
title: "Summarized Repertoire Analysis 3"
output:
  html_document:
    df_print: paged
---


```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
source("Main.R")
library(Peptides)
library(gtools)

knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
 df=data.frame( sampleNames=samples$SampleNames,
                 sampleAttributes=samples$SampleAttributesPrint,
                 donorID=samples$DonorID,
                 CanonicalSampleName = samples$CanonicalSampleName,
                 stringsAsFactors = F)
  df <- df[df$sampleAttributes %in% c("UC Inflamed", "UC Less Inflamed", "UC Non-Inflamed", "Healthy"),]

```

```{r}
getMutationFreq <- function(contigs, sampleType){
    db_obsHeavy <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT",
                                germlineColumn="GERMLINE_IMGT",
                                regionDefinition=IMGT_V_BY_SEGMENTS,
                                frequency=FALSE, 
                                nproc=1)
   db_obsLight <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT_LIGHT",
                                germlineColumn="GERMLINE_IMGT_LIGHT",
                                regionDefinition=IMGT_V_BY_SEGMENTS,
                                frequency=FALSE, 
                                nproc=1)
   
        
   db_obsHeavy <- db_obsHeavy[,c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "mu_count_v_r", "mu_count_v_s")]
   db_obsLight <- db_obsLight[,c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "mu_count_v_r", "mu_count_v_s")]
   
   colnames(db_obsHeavy) <- c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "VH_R", "VH_S")
   colnames(db_obsLight) <- c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "VL_R", "VL_S")

   db_obs_all <- merge(db_obsHeavy, db_obsLight, by=c("CELL", "C_CALL_General", "C_CALL_LIGHT_General"))
   
   
   db_obs_all$V_heavy <- db_obs_all$VH_R + db_obs_all$VH_S
   db_obs_all$V_light <- db_obs_all$VL_R + db_obs_all$VL_S
   
   db_obs_all$selectionPres_VH <- (db_obs_all$VH_R/ db_obs_all$V_heavy)
   db_obs_all$selectionPres_VL <- (db_obs_all$VL_R/ db_obs_all$V_light)
   
   
   db_obs_melted <- melt(db_obs_all[,c("C_CALL_General", "C_CALL_LIGHT_General", "VH_R", "VH_S", "VL_R", "VL_S")], 
                         id.vars = c( "C_CALL_General", "C_CALL_LIGHT_General"))
   
   db_obs_melted$variable <- as.character(db_obs_melted$variable)
   db_obs_melted[db_obs_melted$variable %in% c("VH_R", "VH_S"), "chainT"] <- "VH"
   db_obs_melted[db_obs_melted$variable %in% c("VL_R", "VL_S") & 
                   db_obs_melted$C_CALL_LIGHT_General == "IGL" , "chainT"] <- "VL"
   db_obs_melted[db_obs_melted$variable %in% c("VL_R", "VL_S") & 
                   db_obs_melted$C_CALL_LIGHT_General == "IGK" , "chainT"] <- "VK"

   db_obs_melted$C_CALL_General <- as.character(db_obs_melted$C_CALL_General)
   db_obs_melted$sampleType <- sampleType
   
   db_obs_melted_selectionPres <- melt(db_obs_all[,c("C_CALL_General", "C_CALL_LIGHT_General", "selectionPres_VH", "selectionPres_VL")], 
                                       id.vars = c( "C_CALL_General", "C_CALL_LIGHT_General"))
   db_obs_melted_selectionPres$sampleType= sampleType
   
   return(list(db_obs_melted=db_obs_melted,db_obs_melted_selectionPres=db_obs_melted_selectionPres))
}
```



```{r}
mutationsAll <- data.frame()
mutationsSelectionPres <- data.frame()

for( elem in c("UC Inflamed", "UC Less Inflamed", "UC Non-Inflamed", "Healthy")){
    dfTemp <- df[df$sampleAttributes == elem,]


    for(sName in unique(dfTemp$CanonicalSampleName)){
      print(paste0(elem , " ", sName))
      allContigs <- read.table(paste0(dataDir,"/MergedVDJReplicates/",sName,
                                      "/filtered_single_light_heavy_paired_clone-pass.tab"),
                             sep="\t", header=TRUE, stringsAsFactors = F)
      allContigs <- allContigs[allContigs$C_CALL != "",]
      allContigs$C_CALL_General <- sapply(allContigs$C_CALL, function(x){substr(x,1,4)})
      allContigs$C_CALL_LIGHT_General <- sapply(allContigs$C_CALL_LIGHT, function(x){substr(x,1,3)})
      allContigs <- allContigs[allContigs$C_CALL_LIGHT_General %in% c("IGL", "IGK"),]
      allContigs <- allContigs[allContigs$C_CALL_General %in% c("IGHA", "IGHG", "IGHM"),]

      k <- getMutationFreq(contigs = allContigs, sampleType=elem)
      mutationsAll <- rbind(mutationsAll, k$db_obs_melted)
      mutationsSelectionPres <- rbind(mutationsSelectionPres, k$db_obs_melted_selectionPres)
    }
}

 saveRDS(mutationsAll, paste0(dataDir, "/RDSFiles/mutationsAll.rds"))
 saveRDS(mutationsSelectionPres, paste0(dataDir, "/RDSFiles/mutationsSelectionPres.rds"))
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=8, fig.height=6}
 mutationsAll <- readRDS(paste0(dataDir, "/RDSFiles/mutationsAll.rds"))
 mutationsAll$sampleType <- paste0(as.character(mutationsAll$sampleType), "_",sapply(mutationsAll$variable, function(x){return(strsplit(x,"_")[[1]][2]) }))
 
 mutationsAll$sampleType <- factor(mutationsAll$sampleType,
                                levels = c("Healthy_R","Healthy_S" ,
                                           "UC Non-Inflamed_R","UC Non-Inflamed_S",
                                           "UC Less Inflamed_R", "UC Less Inflamed_S",
                                           "UC Inflamed_R", "UC Inflamed_S"
                                           )) 
 
 cList = list(c("UC Inflamed_R", "UC Inflamed_S"), c("Healthy_R", "Healthy_S"),
              c("UC Less Inflamed_R", "UC Less Inflamed_S"), c( "UC Non-Inflamed_R","UC Non-Inflamed_S"),
              c("Healthy_R", "UC Inflamed_R"), c("UC Less Inflamed_R", "UC Inflamed_R"), c("UC Non-Inflamed_R", "UC Inflamed_R"),
              c("Healthy_S", "UC Inflamed_S"))

k <-  ggplot(mutationsAll, aes(x=sampleType, y=value)) + 
     facet_grid(chainT~C_CALL_General)+
     geom_violin(trim=FALSE, aes(fill=variable))+
     stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")+
     stat_summary(aes(label=round(..y..,2)), fun.y="mean", geom="text", size=5)+
     stat_compare_means(method="t.test",paired = FALSE,
                                comparisons = cList,
                                color="red", method.args = list(alternative = "greater"),
                                label.y = c(50,50,50,50,60,65,70,75), aes(label = ..p.signif..))+
     scale_fill_brewer(palette = "Pastel1")+
     scale_y_continuous(breaks = c(0,10,20,40,60,80), labels = c(0,10,20,40,60,80))+
     xlab("")+
     ylab("Number of mutations in V segment")+
     theme_bw()+
        theme(legend.position = "None", axis.text = element_text(size=16),
              axis.title =  element_text(size=16),strip.text = element_text(size=18),
              axis.text.x = element_text(angle = 90, hjust = 1))

  #pdf(file = paste0(dataDir,"/SummaryFigures/NumberOfMutations.pdf"), width = 15, height = 10)
  plot(k)
  #dev.off()
   
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=8, fig.height=6}
 mutationsSelectionPres <- readRDS(paste0(dataDir, "/RDSFiles/mutationsSelectionPres.rds"))
 mutationsSelectionPres$chainType <- sapply(as.character(mutationsSelectionPres$variable), function(x){return(strsplit(x,"_")[[1]][2]) })
 mutationsSelectionPres[mutationsSelectionPres$chainType == "VL" & mutationsSelectionPres$C_CALL_LIGHT_General == "IGL","chainType"] <- "VL"
 mutationsSelectionPres[mutationsSelectionPres$chainType == "VL" & mutationsSelectionPres$C_CALL_LIGHT_General == "IGK","chainType"] <- "VK"
 
 mutationsSelectionPres$sampleType <- factor(mutationsSelectionPres$sampleType,
                                levels = c("UC Inflamed","UC Less Inflamed","UC Non-Inflamed","Healthy")) 
 
 cList = list(c("UC Inflamed", "UC Less Inflamed"), c("UC Inflamed", "UC Non-Inflamed"), c("UC Non-Inflamed", "Healthy"),
              c("UC Inflamed", "Healthy"), c("UC Less Inflamed", "Healthy"))

k <-  ggplot(mutationsSelectionPres, aes(x=sampleType, y=value)) + 
     facet_grid(chainType~C_CALL_General)+
     geom_violin(trim=FALSE, aes(fill=variable))+
     stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")+
     stat_summary(aes(label=round(..y..,2)), fun.y="mean", geom="text", size=5)+
     stat_compare_means(method="t.test",paired = FALSE,
                                comparisons = cList,
                                color="red", method.args = list(alternative = "greater"),
                                label.y = c(1,1.1,1.2,1.3,1.4), aes(label = ..p.signif..))+
     scale_fill_brewer(palette = "Pastel1")+
     scale_y_continuous(breaks = seq(0,1.6,0.2), labels = seq(0,1.6,0.2))+ylim(0,1.6)+
     xlab("")+
     ylab("Selection pressure (Replacement / (Replacement + Silent))")+
     theme_bw()+
        theme(legend.position = "None", axis.text = element_text(size=13),
              axis.title =  element_text(size=16),strip.text = element_text(size=18),
              axis.text.x = element_text(angle = 90, hjust = 1))

 pdf(file = paste0(dataDir,"/SummaryFigures/MutationsSelectionPressure.pdf"), width = 15, height = 10)
 plot(k)
 dev.off()

```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=13, fig.height=8}
getSomaticMutationBars <- function(contigs, heavyOrLight="heavy", sampleType){
    
    if(heavyOrLight == "heavy"){
      db_obs <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT",
                                germlineColumn="GERMLINE_IMGT",
                                regionDefinition=IMGT_V_BY_REGIONS,
                                frequency=TRUE, 
                                nproc=1)
      muCols <- grep("CELL|mu_freq|C_CALL_General", colnames(db_obs))
      tt <-  db_obs[,muCols]
      
    }else if(heavyOrLight == "light"){
      db_obs <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT_LIGHT",
                                germlineColumn="GERMLINE_IMGT_LIGHT",
                                regionDefinition=IMGT_V_BY_REGIONS,
                                frequency=TRUE, 
                                nproc=1)
      
      db_obs <- db_obs[db_obs$C_CALL_LIGHT_General %in% c("IGK","IGL"),]
        
      muCols <- grep("CELL|mu_freq|C_CALL_LIGHT_General", colnames(db_obs))
      tt <- db_obs[,muCols]
      tt$C_CALL_General <- tt$C_CALL_LIGHT_General
      tt$C_CALL_LIGHT_General <- NULL
    }
  
      db_obsPlot <- melt(tt, id.vars = c("CELL","C_CALL_General"))
      db_obsPlot$variable <- sapply(db_obsPlot$variable, function(x){strsplit(as.character(x),"mu_freq_")[[1]][2]})
      db_obsPlot$region <- sapply(db_obsPlot$variable, function(x){strsplit(x,"_")[[1]][1]})
      db_obsPlot$mutationType <- sapply(db_obsPlot$variable, function(x){strsplit(x,"_")[[1]][2]})
      db_obsPlot$cellRegion <- paste0(db_obsPlot$CELL,"_",db_obsPlot$region,"_",db_obsPlot$C_CALL_General)
      db_obsPlot$variable <- factor(db_obsPlot$variable, levels=c("cdr1_r", "cdr1_s", "cdr2_r", "cdr2_s",
                                                                  "fwr1_r", "fwr1_s", "fwr2_r", "fwr2_s", "fwr3_r", "fwr3_s"))
      db_obsPlot$sampleType <- sampleType
      
     
      return(db_obsPlot)
}

```

```{r}
mutationsAllByRegionHeavy <- data.frame()
mutationsAllByRegionLight <- data.frame()

for( elem in c("UC Inflamed", "UC Less Inflamed", "UC Non-Inflamed", "Healthy")){
    dfTemp <- df[df$sampleAttributes == elem,]


    for(sName in unique(dfTemp$CanonicalSampleName)){
      print(paste0(elem , " ", sName))
      allContigs <- read.table(paste0(dataDir,"/MergedVDJReplicates/",sName,
                                       "/filtered_single_light_heavy_paired_clone-pass.tab"),
                              sep="\t", header=TRUE, stringsAsFactors = F)
      allContigs <- allContigs[allContigs$C_CALL != "",]
      allContigs$C_CALL_General <- sapply(allContigs$C_CALL, function(x){substr(x,1,4)})
      allContigs$C_CALL_LIGHT_General <- sapply(allContigs$C_CALL_LIGHT, function(x){substr(x,1,3)})
      allContigs <- allContigs[allContigs$C_CALL_LIGHT_General %in% c("IGL", "IGK"),]
      allContigs <- allContigs[allContigs$C_CALL_General %in% c("IGHA", "IGHG", "IGHM"),]
      allContigs$CELL <- paste0(sName,"_",allContigs$CELL)
      mutationsAllByRegionHeavy <- rbind(mutationsAllByRegionHeavy, getSomaticMutationBars(contigs = allContigs,
                                                                                 heavyOrLight="heavy",
                                                                                 sampleType=elem))
      mutationsAllByRegionLight <- rbind(mutationsAllByRegionLight, getSomaticMutationBars(allContigs,
                                                                                 heavyOrLight="light",
                                                                                 sampleType=elem))
    }
}


saveRDS(mutationsAllByRegionHeavy, paste0(dataDir, "/RDSFiles/mutationsAllByRegionHeavy.rds"))
saveRDS(mutationsAllByRegionLight, paste0(dataDir, "/RDSFiles/mutationsAllByRegionLight.rds"))

```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=10, fig.height=5}
  mutationsAllByRegionHeavy <- readRDS(paste0(dataDir, "/RDSFiles/mutationsAllByRegionHeavy.rds"))

  mutationsAllByRegionHeavy$sampleType <- paste0(mutationsAllByRegionHeavy$sampleType,"_",mutationsAllByRegionHeavy$mutationType)
  
  mutationsAllByRegionHeavy$sampleType <- factor(mutationsAllByRegionHeavy$sampleType,
                                levels = c("Healthy_r","Healthy_s" ,
                                           "UC Non-Inflamed_r","UC Non-Inflamed_s",
                                           "UC Less Inflamed_r", "UC Less Inflamed_s",
                                           "UC Inflamed_r", "UC Inflamed_s"
                                           )) 
  
  
  ggboxplot(mutationsAllByRegionHeavy, x = "sampleType", y = "value",
          fill = "mutationType",remove = "point", add="mean",add.params = list(color = "red"),
          size = 0.01, bxp.errorbar = T)+
          facet_grid(C_CALL_General~region)+
          stat_compare_means(method="t.test",
                                comparisons = cList,paired=F,method.args = list(alternative = "greater"),
                                color="red",
                                label.y= c(0.4,0.4,0.4,0.4,0.45,0.5), aes(label = ..p.signif..))+
     xlab("")+
     scale_fill_brewer(palette = "Accent")+ylab("Mutation frequency")+
     theme_bw()+
        theme(legend.position = "None", axis.text = element_text(size=13),
              axis.title =  element_text(size=15),strip.text = element_text(size=15),
              axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=13, fig.height=8}
   mutationsAllByRegionLight <- readRDS(paste0(dataDir, "/RDSFiles/mutationsAllByRegionLight.rds"))


   mutationsAllByRegionLight$sampleType <- paste0(mutationsAllByRegionLight$sampleType,"_",mutationsAllByRegionLight$mutationType)
  
  mutationsAllByRegionLight$sampleType <- factor(mutationsAllByRegionLight$sampleType,
                                levels = c("Healthy_R","Healthy_S" ,
                                           "UC Non-Inflamed_R","UC Non-Inflamed_S",
                                           "UC Less Inflamed_R", "UC Less Inflamed_S",
                                           "UC Inflamed_R", "UC Inflamed_S"
                                           )) 

   
  ggboxplot(mutationsAllByRegionLight, x = "sampleType", y = "value",
          fill = "mutationType",remove = "point", add="mean",add.params = list(color = "red"),
          size = 0.01, bxp.errorbar = T)+
          facet_grid(C_CALL_General~region)+
          stat_compare_means(method="t.test",
                                comparisons = cList,paired=F,method.args = list(alternative = "greater"),
                                color="red",
                                label.y= c(0.4,0.4,0.4,0.4,0.45,0.5), aes(label = ..p.signif..))+
     xlab("")+ylim(c(0,0.6))+
     scale_fill_brewer(palette = "Set2")+ylab("Mutation frequency")+
     theme_bw()+
        theme(legend.position = "None", axis.text = element_text(size=13),
              axis.title =  element_text(size=15),strip.text = element_text(size=15),
              axis.text.x = element_text(angle = 90, hjust = 1))

```

