---
title: "B cell transcriptomes"
output:
  html_document:
    df_print: paged
---

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
source("Main.R")
set.seed(42)
library(knitr)
library(cowplot)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
library(RColorBrewer)

#reticulate::use_python("/anaconda3/bin/python", required = T)

samps <-  readRDS(paste0(dataDir, "/RDSFiles/allSamplesReplicatesMerged.rds"))
IG_genes <- read.csv(paste0(dataDir,"IG_Genes.txt"), sep = '\t', stringsAsFactors = F)

```

```{r  echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.height=10, fig.width=10}
     df=data.frame( sampleNames=sampleNames,
                sampleAttributes=sampleAttributesPrint,
                donorID=as.factor(donorID), stringsAsFactors = F)


     for(i in 1:length(samps)){
       serObj <- samps[[i]]
       print(serObj$orig.ident)
       print(serObj$stim)
       print(dim(serObj@assays$RNA))
       samps[[i]] <- serObj[rownames(serObj[["RNA"]]) %ni% c(as.character(IG_genes$Gene.name),
                                                             "CH17-262H11.1", "AC233755.1","CH17-212P11.4", "AC233755.2", "CH17-224D4.1"),]
     }
    
      

      immune.anchors <- FindIntegrationAnchors(object.list = samps, k.filter = NA, k.score=60)
      saveRDS(immune.anchors, paste0(dataDir, "/RDSFiles/integratedAnchors_1.rds"))
      immune.anchors <- readRDS(paste0(dataDir, "/RDSFiles/integratedAnchors_1.rds"))
      immune.combined <- IntegrateData(anchorset = immune.anchors,
                                       dims = 1:50)
      
      saveRDS(immune.combined, paste0(dataDir, "/RDSFiles/immuneCombined_0.rds"))
    
      #immune.combined <- readRDS(paste0(dataDir, "/RDSFiles/immuneCombined.rds")) 
      immune.combined <- ScaleData(immune.combined, verbose = FALSE)
      immune.combined <- RunPCA(immune.combined, npcs = 50, verbose = FALSE)
      Idents(immune.combined) <- "stim"
    
      immune.combined <- FindNeighbors( immune.combined, dims = 1:50)
      immune.combined <- FindClusters( immune.combined, resolution = 0.2)
     
      saveRDS(immune.combined, paste0(dataDir, "/RDSFiles/immuneCombined_1.rds"))
      immune.combined <- RunTSNE( immune.combined, dims = 1:50)
      immune.combined <- RunUMAP( immune.combined, dims = 1:50)
    
     saveRDS(immune.combined, paste0(dataDir, "/RDSFiles/immuneCombined_2.rds"))

    #immune.combined <- readRDS(paste0(dataDir, "/RDSFiles/immuneCombined3.rds"))

    # print(DimPlot(immune.combined, reduction = "umap", split.by = "stim", pt.size = 0.5, label = TRUE, label.size = 7)+
    #         theme(legend.text = element_text(size=20), strip.text = element_text(size=25))+
    #         scale_color_manual(values = colorRampPalette(brewer.pal(12, "Accent"))(length(levels(immune.combined$seurat_clusters)))))
    # 
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.height=9, fig.width=9}
    #obj.markers <- FindAllMarkers(immune.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
    #obj.markers <- obj.markers[obj.markers$p_val_adj < 0.1,]

    #saveRDS( obj.markers, paste0(dataDir, "/RDSFiles/ obj.markers2.rds"))
    # obj.markers <- readRDS(paste0(dataDir, "/RDSFiles/ obj.markers2.rds"))
    # top10 <- obj.markers  %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
    # print(DoHeatmap(immune.combined, features = top10$gene) + 
    #       theme(axis.text.y =element_text(size=6)))
```

```{r}
  # Idents(immune.combined) <- "stim"
  # uc.response <- FindMarkers(immune.combined, ident.1 = "UC_INF", ident.2 = "Healthy", verbose = FALSE)
  # print(uc.response)
  # 
  # uc.response2 <- FindMarkers(immune.combined, ident.1 = "UC_INF", ident.2 = "UC_LessINF", verbose = FALSE)
  # print(uc.response2)
  # 
  
```

