---
title: "Supplement Figure 2D"
output:
  html_document:
    df_print: paged
---

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
source("Main.R")

knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
```


```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
 df=data.frame( sampleNames=samples$SampleNames,
                 sampleAttributes=samples$SampleAttributesPrint,
                 donorID=samples$DonorID,
                 CanonicalSampleName = samples$CanonicalSampleName,
                 stringsAsFactors = F)
  df <- df[df$sampleAttributes %in% c("UC Inflamed", "UC Less Inflamed", "UC Non-Inflamed", "Healthy"),]

```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
getMutationFreq <- function(contigs, sampleType){
    db_obsHeavy <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT",
                                germlineColumn="GERMLINE_IMGT",
                                regionDefinition=IMGT_V_BY_SEGMENTS,
                                frequency=FALSE, 
                                nproc=1)
   db_obsLight <- observedMutations(contigs,
                                sequenceColumn="SEQUENCE_IMGT_LIGHT",
                                germlineColumn="GERMLINE_IMGT_LIGHT",
                                regionDefinition=IMGT_V_BY_SEGMENTS,
                                frequency=FALSE, 
                                nproc=1)
   
        
   db_obsHeavy <- db_obsHeavy[,c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "mu_count_v_r", "mu_count_v_s","SAMPLENAME","SAMPLETYPE","CLONE","NumberOfClonalCells","sampleRegion","SAMPLETYPEPRINT", "donorID")]
   db_obsLight <- db_obsLight[,c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "mu_count_v_r", "mu_count_v_s", "SAMPLENAME","SAMPLETYPE","CLONE","NumberOfClonalCells","sampleRegion","SAMPLETYPEPRINT", "donorID")]
   
   colnames(db_obsHeavy) <- c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "VH_R", "VH_S", "SAMPLENAME","SAMPLETYPE","CLONE","NumberOfClonalCells","sampleRegion","SAMPLETYPEPRINT", "donorID")
   colnames(db_obsLight) <- c("CELL","C_CALL_General", "C_CALL_LIGHT_General", "VL_R", "VL_S", "SAMPLENAME","SAMPLETYPE","CLONE","NumberOfClonalCells","sampleRegion","SAMPLETYPEPRINT", "donorID")

   db_obs_all <- merge(db_obsHeavy, db_obsLight, by=c("SAMPLENAME","SAMPLETYPE","CLONE","NumberOfClonalCells","sampleRegion","SAMPLETYPEPRINT","CELL", "C_CALL_General", "C_CALL_LIGHT_General","donorID"))
   
   
   db_obs_all$V_heavy <- db_obs_all$VH_R + db_obs_all$VH_S
   db_obs_all$V_light <- db_obs_all$VL_R + db_obs_all$VL_S
   
   db_obs_all$selectionPres_VH <- (db_obs_all$VH_R/ db_obs_all$V_heavy)
   db_obs_all$selectionPres_VL <- (db_obs_all$VL_R/ db_obs_all$V_light)
   
   
   db_obs_melted <- melt(db_obs_all,id.vars = c( "SAMPLENAME","SAMPLETYPE","CLONE","NumberOfClonalCells","sampleRegion","SAMPLETYPEPRINT","CELL","C_CALL_General",  "C_CALL_LIGHT_General","donorID","selectionPres_VH","selectionPres_VL","V_heavy","V_light"))
   
   db_obs_melted$variable <- as.character(db_obs_melted$variable)
   db_obs_melted[db_obs_melted$variable %in% c("VH_R", "VH_S"), "chainT"] <- "VH"
   db_obs_melted[db_obs_melted$variable %in% c("VL_R", "VL_S") & 
                   db_obs_melted$C_CALL_LIGHT_General == "IGL" , "chainT"] <- "VL"
   db_obs_melted[db_obs_melted$variable %in% c("VL_R", "VL_S") & 
                   db_obs_melted$C_CALL_LIGHT_General == "IGK" , "chainT"] <- "VK"

   db_obs_melted$C_CALL_General <- as.character(db_obs_melted$C_CALL_General)
   
   db_obs_melted_selectionPres <- melt(db_obs_all[,c("SAMPLENAME","SAMPLETYPE","CLONE","NumberOfClonalCells","sampleRegion",
                                                     "SAMPLETYPEPRINT","CELL",
                                                     "C_CALL_General", "C_CALL_LIGHT_General",
                                                     "donorID","selectionPres_VH","selectionPres_VL")], 
                                       id.vars = c("SAMPLENAME","SAMPLETYPE","CLONE","NumberOfClonalCells",
                                                   "sampleRegion","SAMPLETYPEPRINT","CELL", "C_CALL_General",
                                                   "C_CALL_LIGHT_General","donorID"))

   return(list(db_obs_melted=db_obs_melted,db_obs_melted_selectionPres=db_obs_melted_selectionPres))
}
```

```{r}
allClones = combineAllClones()
mutationsAll <- data.frame()
mutationsSelectionPres <- data.frame()
```


```{r}

for( elem in c("UC_INF", "UC_LessINF", "UC_NonINF", "Healthy")){
    allClonesTemp <- allClones[allClones$SAMPLETYPE == elem,]

      
    k <- getMutationFreq(contigs = allClonesTemp, sampleType=elem)
    mutationsAll <- rbind(mutationsAll, k$db_obs_melted)
    mutationsSelectionPres <- rbind(mutationsSelectionPres, k$db_obs_melted_selectionPres)
}

saveRDS(mutationsAll, paste0(dataDir, "/RDSFiles/mutationsAll_1.rds"))
saveRDS(mutationsSelectionPres, paste0(dataDir, "/RDSFiles/mutationsSelectionPres_1.rds"))
```



```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=7, fig.height=5}
 mutationsSelectionPres <- readRDS(paste0(dataDir, "/RDSFiles/mutationsSelectionPres_1.rds"))
 mutationsSelectionPres <- mutationsSelectionPres[mutationsSelectionPres$C_CALL_General %in% c("IGHA", "IGHG", "IGHM"),]
 mutationsSelectionPres$chainType <- sapply(as.character(mutationsSelectionPres$variable), function(x){return(strsplit(x,"_")[[1]][2]) })
 mutationsSelectionPres[mutationsSelectionPres$chainType == "VL" & mutationsSelectionPres$C_CALL_LIGHT_General == "IGL","chainType"] <- "VL"
 mutationsSelectionPres[mutationsSelectionPres$chainType == "VL" & mutationsSelectionPres$C_CALL_LIGHT_General == "IGK","chainType"] <- "VK"
 
 
 mutationsSelectionPres$SAMPLETYPEPRINT <- factor(mutationsSelectionPres$SAMPLETYPEPRINT,
                                levels = c("Healthy","UC Non-Inflamed","UC Less Inflamed","UC Inflamed")) 
 
 cList = list(c("UC Inflamed", "UC Less Inflamed"), c("UC Inflamed", "UC Non-Inflamed"), c("UC Non-Inflamed", "Healthy"),
              c("UC Inflamed", "Healthy"))

k <-  ggplot(mutationsSelectionPres, aes(x=SAMPLETYPEPRINT, y=value)) + 
     facet_grid(chainType~C_CALL_General)+
     geom_violin(trim=FALSE, aes(fill=variable))+
     stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")+
     stat_summary(aes(label=round(..y..,2)), fun.y="mean", geom="text", size=5)+
     stat_compare_means(method="t.test",paired = FALSE,
                                comparisons = cList,
                                color="red", method.args = list(alternative = "greater"),
                                label.y = c(1,1.1,1.2,1.3,1.4), aes(label = ..p.signif..))+
     scale_fill_brewer(palette = "Pastel1")+
     scale_y_continuous(breaks = seq(0,1.6,0.2), labels = seq(0,1.6,0.2))+ylim(0,1.6)+
     xlab("")+
     ylab("Selection pressure (Replacement / (Replacement + Silent))")+
     theme_bw()+
        theme(legend.position = "None", axis.text = element_text(size=13),
              axis.title =  element_text(size=16),strip.text = element_text(size=18),
              axis.text.x = element_text(angle = 90, hjust = 1, size=18))

 pdf(file = "./PDFFigures/S2D.pdf", width = 15,  height = 9)
  plot(k)
 dev.off()

```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=6, fig.height=4}
 mutationsNo <- readRDS(paste0(dataDir, "/RDSFiles/mutationsAll_1.rds"))
 mutationsNo <- mutationsNo[mutationsNo$C_CALL_General %in% c("IGHA", "IGHG", "IGHM"),]
 mutationsNo$chainType <- sapply(as.character(mutationsNo$variable), function(x){return(strsplit(x,"_")[[1]][2]) })
 mutationsNo <- mutationsNo[mutationsNo$chainT == "VH",]
 
 mutationsNo$SAMPLETYPEPRINT <- as.character( mutationsNo$SAMPLETYPEPRINT)
 mutationsNo$SAMPLETYPEPRINT <- sapply( mutationsNo$SAMPLETYPEPRINT, function(x){strsplit(x,"_")[[1]][1]})
 
mutationsNo$SAMPLETYPEPRINT <- factor(mutationsNo$SAMPLETYPEPRINT,
                                levels = c("Healthy","UC Non-Inflamed","UC Less Inflamed","UC Inflamed")) 
 
 cList = list(c("UC Inflamed", "UC Less Inflamed"), c("UC Inflamed", "UC Non-Inflamed"), c("UC Non-Inflamed", "Healthy"),
              c("UC Inflamed", "Healthy"))

k <-  ggplot(mutationsNo, aes(x=SAMPLETYPEPRINT, y=value)) + 
     facet_grid(variable~C_CALL_General)+
     geom_violin(trim=FALSE, aes(fill=variable))+
     stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")+
     stat_summary(aes(label=round(..y..,2)), fun.y="mean", geom="text", size=5)+
     stat_compare_means(method="t.test",paired = FALSE,
                                comparisons = cList,
                                color="red", 
                                label.y = c(50,54,58,62,66), aes(label = ..p.signif..))+
     scale_fill_brewer(palette = "Set3")+
    # scale_y_continuous(breaks = seq(0,1.6,0.2), labels = seq(0,1.6,0.2))+ylim(0,1.6)+
     xlab("")+
     ylab("Number of mutations")+
     theme_bw()+
        theme(legend.position = "None", axis.text = element_text(size=13),
              axis.title =  element_text(size=16),strip.text = element_text(size=18),
              axis.text.x = element_text(angle = 90, hjust = 1, size=18))

 pdf(file = "./PDFFigures/S2F.pdf", width = 12,  height = 7)
  plot(k)
 dev.off()

```
